package crimera.patches.twitter.misc.bringbacktwitter.strings

object tr {
    val values = mapOf(
        "button_action_add_tweet" to "Bir tweet ekle",
        "button_action_options_tweet" to "Tweet seçenekleri",
        "button_action_retweet" to "Retweet",
        "button_new_tweet" to "Yeni tweet",
        "button_status_retweeted" to "Retweet (retweetlendi)",
        "chrome_action_post" to "Tweetle",
        "ps__share_post_tweet" to "Tweetle",
        "rux_landing_page_title" to "Tweetle",
        "tweet_fab_item" to "Tweetle",
        "tweet_title" to "Tweet",
        "search_twitter" to "Twitter\\'da Ara",
        "search_hint" to "Twitter\\'da Ara",
        "ps__accessibility_retweet_broadcast_button" to "Retweet",
        "shortcut_retweet_tweet" to "Retweet",
        "social_you_retweeted" to "Retweetledin",
        "composer_hint_self_thread" to "Başka bir tweet ekle",
        "confirm_delete_shared_tweet_description" to "Bu tweet\\'i silmek istediğinizden emin misiniz?",
        "confirm_delete_shared_tweet_title" to "Tweet\\'i sil",
        "conversation_control_reply_restricted_dialog_title" to "Tweet gönderilmedi",
        "conversation_control_reply_restricted_error" to "Tweet gönderilmedi. Yanıtlar kısıtlıdır.",
        "conversations_alternative_reply_hint" to "Yanıtınızı tweetleyin",
        "conversations_other_tweets" to "Diğer tweetler",
        "curation_i_dont_like_this_tweet" to "Bu tweet\\'i beğenmedim",
        "date_posted" to "Tweet tarihi",
        "post_tweet" to "Tweetle",
        "deleted_tweet_title" to "Bu tweet silindi.",
        "dm_sensitive_tweet_interstitial_header" to "Bu tweet hassas içerik içerebilir",
        "dm_untrusted_tweet_interstitial_header" to "Bu tweet gizlenmiş",
        "empty_profile_tweets_tab_title" to "Henüz tweetlemediniz",
        "feedback_action_report_tweet" to "Tweet\\'i bildir",
        "feedback_tweet_unavailable" to "Bu tweet mevcut değil.",
        "filter_item_tweets" to "Tweetler",
        "filter_item_tweets_and_replies" to "Tweetler ve yanıtlar",
        "profile_tab_title_timeline" to "Tweetler",
        "users_turn_off_retweets" to "Retweetleri kapat",
        "tweets_retweet" to "Retweet",
        "tweets_retweeted" to "%s retweetledi",
        "tweets_undo_retweet_vertical" to "Retweeti geri al",
        "users_turn_on_retweets" to "Retweetleri aç",
        "ps__post_broadcast_twitter" to "Twitter\\'da tweetle",
        "ps__retweet_broadcast_action" to "Twitter\\'da retweetle",
        "retweeters_title" to "Retweetleyenler",
        "icon_view_tweet_activity" to "Tweet etkinliğini görüntüle",
        "a11y_views_text" to "Tweet etkinliğini görüntüle",
        "tweet_analytics_title" to "Tweet etkinliği",
        "tweets_delete_title" to "Tweet\\'i sil",
        "share_tweet_sheet_title" to "Tweet\\'i paylaş",
        "view_quote_tweet" to "Tweet\\'i görüntüle",
        "view_tweet" to "Tweet\\'i görüntüle",
        "view_tweet_text" to "Tweet\\'i görüntüle",
        "quote_label_subtitle" to "Bu tweet\\'i paylaşmadan önce bir yorum, fotoğraf veya GIF ekleyin",
        "retweet_label_subtitle" to "Bu tweet\\'i takipçilerinizle paylaşın",
        "tweet_added_to_your_bookmarks" to "Tweet, yer işaretlerine eklendi",
        "tweet_author" to "Tweet yazarı",
        "tweets_retweeted_accessibility_description" to "%s tarafından tweetlendi",
        "tweets_topic_accessibility_description" to "%s konusundan tweet",
        "tweets_unauthorized_error" to "Üzgünüz, bu tweetleri görüntüleme yetkiniz yok.",
        "ps__posted_on_twitter" to "*%s* tarafından tweetlendi",
        "ps__retweeted_on_twitter" to "*%s* tarafından retweetlendi",
        "tweet_removed_from_your_bookmarks" to "Tweet, yer işaretlerinizden kaldırıldı"
    )
}