package app.crimera.patches.twitter.misc.appicon

/**
 * List of XML icon files in the mipmap-anydpi directory.
 * This list can be auto-generated by a build script.
 */
internal val mipmapAnydpiFiles =
    arrayOf(
        "ic_seasonal_anzac.xml",
        "ic_seasonal_autumn_2021.xml",
        "ic_seasonal_autumn_2022.xml",
        "ic_seasonal_barbie.xml",
        "ic_seasonal_beijing_olympics_1.xml",
        "ic_seasonal_beijing_olympics_2.xml",
        "ic_seasonal_black_history.xml",
        "ic_seasonal_daytona.xml",
        "ic_seasonal_easter.xml",
        "ic_seasonal_eurovisionfinal.xml",
        "ic_seasonal_formulaone.xml",
        "ic_seasonal_halloween_2021.xml",
        "ic_seasonal_halloween_2022.xml",
        "ic_seasonal_holi.xml",
        "ic_seasonal_kentucky_derby.xml",
        "ic_seasonal_lunar_new_year_1.xml",
        "ic_seasonal_lunar_new_year_2.xml",
        "ic_seasonal_masters.xml",
        "ic_seasonal_may_the_fourth.xml",
        "ic_seasonal_mlb.xml",
        "ic_seasonal_mothers_day.xml",
        "ic_seasonal_nba_2.xml",
        "ic_seasonal_nba.xml",
        "ic_seasonal_ncaa.xml",
        "ic_seasonal_newzealand_pride_1.xml",
        "ic_seasonal_newzealand_pride_2.xml",
        "ic_seasonal_pridesouthern.xml",
        "ic_seasonal_ramadan.xml",
        "ic_seasonal_south_spring_2021.xml",
        "ic_seasonal_south_spring_2022.xml",
        "ic_seasonal_stpatricks_day.xml",
        "ic_seasonal_summer_1.xml",
        "ic_seasonal_summer_2.xml",
        "ic_seasonal_thanksgiving_1.xml",
        "ic_seasonal_thanksgiving_2.xml",
        "ic_seasonal_winter_1.xml",
        "ic_seasonal_winter_2.xml",
        "ic_seasonal_womansday.xml",
    )

internal val mipmapxxhdpiFiles =
    arrayOf(
        "ic_seasonal_anzac_background.webp",
        "ic_seasonal_autumn_2021_background.webp",
        "ic_seasonal_autumn_2022_background.webp",
        "ic_seasonal_barbie_background.webp",
        "ic_seasonal_beijing_olympics_1_background.webp",
        "ic_seasonal_beijing_olympics_2_background.webp",
        "ic_seasonal_black_history_background.webp",
        "ic_seasonal_daytona_background.webp",
        "ic_seasonal_easter_background.webp",
        "ic_seasonal_eurovisionfinal_background.webp",
        "ic_seasonal_formulaone_background.webp",
        "ic_seasonal_halloween_2021_background.webp",
        "ic_seasonal_halloween_2022_background.webp",
        "ic_seasonal_holi_background.webp",
        "ic_seasonal_kentucky_derby_background.webp",
        "ic_seasonal_lunar_new_year_1_background.webp",
        "ic_seasonal_lunar_new_year_2_background.webp",
        "ic_seasonal_masters_background.webp",
        "ic_seasonal_may_the_fourth_background.webp",
        "ic_seasonal_mlb_background.webp",
        "ic_seasonal_mothers_day_background.webp",
        "ic_seasonal_nba_2_background.webp",
        "ic_seasonal_nba_background.webp",
        "ic_seasonal_ncaa_background.webp",
        "ic_seasonal_newzealand_pride_1_background.webp",
        "ic_seasonal_newzealand_pride_2_background.webp",
        "ic_seasonal_pridesouthern_background.webp",
        "ic_seasonal_ramadan_background.webp",
        "ic_seasonal_south_spring_2021_background.webp",
        "ic_seasonal_south_spring_2022_background.webp",
        "ic_seasonal_stpatricks_day_background.webp",
        "ic_seasonal_summer_1_background.webp",
        "ic_seasonal_summer_2_background.webp",
        "ic_seasonal_thanksgiving_1_background.webp",
        "ic_seasonal_thanksgiving_2_background.webp",
        "ic_seasonal_winter_1_background.webp",
        "ic_seasonal_winter_2_background.webp",
        "ic_seasonal_womansday_background.webp",
    )

data class IconConfig(
    val name: String,
    val iconResource: String,
    val roundIconResource: String,
)

val iconsListForManifest =
    listOf(
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon100",
            iconResource = "@mipmap/ic_seasonal_anzac",
            roundIconResource = "@mipmap/ic_seasonal_anzac",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon101",
            iconResource = "@mipmap/ic_seasonal_autumn_2021",
            roundIconResource = "@mipmap/ic_seasonal_autumn_2021",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon102",
            iconResource = "@mipmap/ic_seasonal_autumn_2022",
            roundIconResource = "@mipmap/ic_seasonal_autumn_2022",
        ),
    )
