package app.crimera.patches.twitter.misc.appicon

/**
 * List of XML icon files in the mipmap-anydpi directory.
 * This list can be auto-generated by a build script.
 */
internal val mipmapAnydpiFiles =
    arrayOf(
        "ic_seasonal_anzac.xml",
        "ic_seasonal_autumn_2021.xml",
        "ic_seasonal_autumn_2022.xml",
        "ic_seasonal_barbie.xml",
        "ic_seasonal_beijing_olympics_1.xml",
        "ic_seasonal_beijing_olympics_2.xml",
        "ic_seasonal_black_history.xml",
        "ic_seasonal_daytona.xml",
        "ic_seasonal_easter.xml",
        "ic_seasonal_eurovisionfinal.xml",
        "ic_seasonal_formulaone.xml",
        "ic_seasonal_halloween_2021.xml",
        "ic_seasonal_halloween_2022.xml",
        "ic_seasonal_holi.xml",
        "ic_seasonal_kentucky_derby.xml",
        "ic_seasonal_lunar_new_year_1.xml",
        "ic_seasonal_lunar_new_year_2.xml",
        "ic_seasonal_masters.xml",
        "ic_seasonal_may_the_fourth.xml",
        "ic_seasonal_mlb.xml",
        "ic_seasonal_mothers_day.xml",
        "ic_seasonal_nba_2.xml",
        "ic_seasonal_nba.xml",
        "ic_seasonal_ncaa.xml",
        "ic_seasonal_newzealand_pride_1.xml",
        "ic_seasonal_newzealand_pride_2.xml",
        "ic_seasonal_pridesouthern.xml",
        "ic_seasonal_ramadan.xml",
        "ic_seasonal_south_spring_2021.xml",
        "ic_seasonal_south_spring_2022.xml",
        "ic_seasonal_stpatricks_day.xml",
        "ic_seasonal_summer_1.xml",
        "ic_seasonal_summer_2.xml",
        "ic_seasonal_thanksgiving_1.xml",
        "ic_seasonal_thanksgiving_2.xml",
        "ic_seasonal_winter_1.xml",
        "ic_seasonal_winter_2.xml",
        "ic_seasonal_womansday.xml",
    )

internal val iconBackgroundFiles =
    arrayOf(
        "ic_seasonal_anzac_background.webp",
        "ic_seasonal_autumn_2021_background.webp",
        "ic_seasonal_autumn_2022_background.webp",
        "ic_seasonal_barbie_background.webp",
        "ic_seasonal_beijing_olympics_1_background.webp",
        "ic_seasonal_beijing_olympics_2_background.webp",
        "ic_seasonal_black_history_background.webp",
        "ic_seasonal_daytona_background.webp",
        "ic_seasonal_easter_background.webp",
        "ic_seasonal_eurovisionfinal_background.webp",
        "ic_seasonal_formulaone_background.webp",
        "ic_seasonal_halloween_2021_background.webp",
        "ic_seasonal_halloween_2022_background.webp",
        "ic_seasonal_holi_background.webp",
        "ic_seasonal_kentucky_derby_background.webp",
        "ic_seasonal_lunar_new_year_1_background.webp",
        "ic_seasonal_lunar_new_year_2_background.webp",
        "ic_seasonal_masters_background.webp",
        "ic_seasonal_may_the_fourth_background.webp",
        "ic_seasonal_mlb_background.webp",
        "ic_seasonal_mothers_day_background.webp",
        "ic_seasonal_nba_2_background.webp",
        "ic_seasonal_nba_background.webp",
        "ic_seasonal_ncaa_background.webp",
        "ic_seasonal_newzealand_pride_1_background.webp",
        "ic_seasonal_newzealand_pride_2_background.webp",
        "ic_seasonal_pridesouthern_background.webp",
        "ic_seasonal_ramadan_background.webp",
        "ic_seasonal_south_spring_2021_background.webp",
        "ic_seasonal_south_spring_2022_background.webp",
        "ic_seasonal_stpatricks_day_background.webp",
        "ic_seasonal_summer_1_background.webp",
        "ic_seasonal_summer_2_background.webp",
        "ic_seasonal_thanksgiving_1_background.webp",
        "ic_seasonal_thanksgiving_2_background.webp",
        "ic_seasonal_winter_1_background.webp",
        "ic_seasonal_winter_2_background.webp",
        "ic_seasonal_womansday_background.webp",
    )

data class IconConfig(
    val name: String,
    val iconResource: String,
)

val iconsListForManifest =
    listOf(
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon100",
            iconResource = "@mipmap/ic_seasonal_autumn_2021",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon101",
            iconResource = "@mipmap/ic_seasonal_autumn_2022",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon102",
            iconResource = "@mipmap/ic_seasonal_south_spring_2021",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon103",
            iconResource = "@mipmap/ic_seasonal_south_spring_2022",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon104",
            iconResource = "@mipmap/ic_seasonal_winter_1",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon105",
            iconResource = "@mipmap/ic_seasonal_winter_2",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon106",
            iconResource = "@mipmap/ic_seasonal_summer_1",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon107",
            iconResource = "@mipmap/ic_seasonal_summer_2",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon108",
            iconResource = "@mipmap/ic_seasonal_beijing_olympics_1",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon109",
            iconResource = "@mipmap/ic_seasonal_beijing_olympics_2",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon110",
            iconResource = "@mipmap/ic_seasonal_daytona",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon111",
            iconResource = "@mipmap/ic_seasonal_formulaone",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon112",
            iconResource = "@mipmap/ic_seasonal_kentucky_derby",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon113",
            iconResource = "@mipmap/ic_seasonal_mlb",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon114",
            iconResource = "@mipmap/ic_seasonal_nba",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon115",
            iconResource = "@mipmap/ic_seasonal_nba_2",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon116",
            iconResource = "@mipmap/ic_seasonal_ncaa",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon117",
            iconResource = "@mipmap/ic_seasonal_masters",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon118",
            iconResource = "@mipmap/ic_seasonal_mothers_day",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon119",
            iconResource = "@mipmap/ic_seasonal_womansday",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon120",
            iconResource = "@mipmap/ic_seasonal_halloween_2021",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon121",
            iconResource = "@mipmap/ic_seasonal_halloween_2022",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon122",
            iconResource = "@mipmap/ic_seasonal_holi",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon123",
            iconResource = "@mipmap/ic_seasonal_stpatricks_day",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon124",
            iconResource = "@mipmap/ic_seasonal_easter",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon125",
            iconResource = "@mipmap/ic_seasonal_anzac",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon126",
            iconResource = "@mipmap/ic_seasonal_ramadan",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon127",
            iconResource = "@mipmap/ic_seasonal_black_history",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon128",
            iconResource = "@mipmap/ic_seasonal_eurovisionfinal",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon129",
            iconResource = "@mipmap/ic_seasonal_lunar_new_year_1",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon130",
            iconResource = "@mipmap/ic_seasonal_lunar_new_year_2",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon131",
            iconResource = "@mipmap/ic_seasonal_may_the_fourth",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon132",
            iconResource = "@mipmap/ic_seasonal_barbie",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon133",
            iconResource = "@mipmap/ic_seasonal_thanksgiving_1",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon134",
            iconResource = "@mipmap/ic_seasonal_thanksgiving_2",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon135",
            iconResource = "@mipmap/ic_seasonal_pridesouthern",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon136",
            iconResource = "@mipmap/ic_seasonal_newzealand_pride_1",
        ),
        IconConfig(
            name = "com.twitter.subscriptions.appicon.implementation.icon137",
            iconResource = "@mipmap/ic_seasonal_newzealand_pride_2",
        ),
    )
