package crimera.patches.twitter.misc.bringbacktwitter.strings

object hi {
    val values = mapOf(
        "button_action_add_tweet" to "एक ट्वीट जोड़ें",
        "button_action_options_tweet" to "ट्वीट विकल्प",
        "button_action_retweet" to "रीट्वीट",
        "button_new_tweet" to "नया ट्वीट",
        "button_status_retweeted" to "रीट्वीट (रीट्वीट कियाहुआ)",
        "chrome_action_post" to "ट्वीट",
        "ps__share_post_tweet" to "ट्वीट",
        "rux_landing_page_title" to "ट्वीट",
        "tweet_fab_item" to "ट्वीट",
        "tweet_title" to "ट्वीट",
        "search_twitter" to "Twitter पर खोजें",
        "search_hint" to "Twitter पर खोजें",
        "ps__accessibility_retweet_broadcast_button" to "रीट्वीट",
        "shortcut_retweet_tweet" to "रीट्वीट",
        "social_you_retweeted" to "आपने रीट्वीट किया",
        "composer_hint_self_thread" to "एक और ट्वीट जोड़ें",
        "confirm_delete_shared_tweet_description" to "क्या आप वाकई इस ट्वीट को हटाना चाहते हैं?",
        "confirm_delete_shared_tweet_title" to "ट्वीट हटाएं",
        "conversation_control_reply_restricted_dialog_title" to "ट्वीट भेजा नहीं गया",
        "conversation_control_reply_restricted_error" to "ट्वीट भेजा नहीं गया. जवाब प्रतिबंधित हैं|",
        "conversations_alternative_reply_hint" to "अपना जवाब ट्वीट करें",
        "conversations_other_tweets" to "अन्य ट्वीट",
        "curation_i_dont_like_this_tweet" to "मुझे यह ट्वीट पसंद नहीं आया",
        "date_posted" to "पोस्ट करने का दिनांक",
        "post_tweet" to "ट्वीट",
        "deleted_tweet_title" to "इस ट्वीट को मिटा दिया गया है|",
        "dm_sensitive_tweet_interstitial_header" to "इस ट्वीट में संवेदनशील सामग्री हो सकती है",
        "dm_untrusted_tweet_interstitial_header" to "यह ट्वीट छिपा हुआ है",
        "empty_profile_tweets_tab_title" to "आपने अभी तक ट्वीट नहीं किया है",
        "feedback_action_report_tweet" to "ट्वीट की रिपोर्ट करें",
        "feedback_tweet_unavailable" to "यह ट्वीट अनुपलब्ध है|",
        "filter_item_tweets" to "ट्वीट्स",
        "filter_item_tweets_and_replies" to "टट्वीट्स और जवाब",
        "profile_tab_title_timeline" to "ट्वीट्स",
        "users_turn_off_retweets" to "रीट्वीट बंद करें",
        "tweets_retweet" to "रिट्वीट",
        "tweets_retweeted" to "%s ने रीट्वीट किया",
        "tweets_undo_retweet_vertical" to "रीट्वीट पूर्ववत करें",
        "users_turn_on_retweets" to "रीट्वीट चालू करें",
        "ps__post_broadcast_twitter" to "ट्वीट on Twitter",
        "ps__retweet_broadcast_action" to "Twitter पर पोस्ट करें",
        "retweeters_title" to "के द्वारा रिट्विट",
        "icon_view_tweet_activity" to "ट्वीट गतिविधि देखें",
        "a11y_views_text" to "ट्वीट गतिविधि देखें",
        "tweet_analytics_title" to "ट्वीट गतिविधि",
        "tweets_delete_title" to "ट्वीट को मिटा दें?",
        "share_tweet_sheet_title" to "ट्वीट शेयर करें",
        "view_quote_tweet" to "ट्वीट देखें",
        "view_tweet" to "ट्वीट देखें",
        "view_tweet_text" to "ट्वीट देखें",
        "quote_label_subtitle" to "इस ट्वीट को शेयर करने से पहले कोई टिप्पणी, फ़ोटो या GIF जोड़ें",
        "retweet_label_subtitle" to "अपने फ़ॉलोअर्स के साथ इस ट्वीट को शेयर करे",
        "tweet_added_to_your_bookmarks" to ">ट्वीट को आपके बुकमार्क में जोड़ा गया<",
        "tweet_author" to ">ट्वीट का लेखक<",
        "tweets_retweeted_accessibility_description" to "%s द्वारा रीट्वीट",
        "tweets_topic_accessibility_description" to ">विषय के ट्वीट \"%s\"<",
        "tweets_unauthorized_error" to "क्षमा करें, आप इन ट्वीट्स को देखने के लिए अधिकृत नहीं हैं|",
        "ps__posted_on_twitter" to "*%s* ने इस पर पोस्ट किया",
        "ps__retweeted_on_twitter" to "*%s* ने इस पर रीट्वीट किया",
        "tweet_removed_from_your_bookmarks" to "ट्वीट को आपके बुकमार्क से निकाल दिया गया"
    )
}