package crimera.patches.twitter.misc.bringbacktwitter.strings

object ru {
    val values = mapOf(
        "button_action_add_tweet" to "Добавить твит",
        "button_action_options_tweet" to "Опции",
        "button_action_retweet" to "Ретвитнуть",
        "button_new_tweet" to "Новый твит",
        "button_status_retweeted" to "Ретвитнуто",
        "chrome_action_post" to "Твитнуть",
        "ps__share_post_tweet" to "Твитнуть",
        "rux_landing_page_title" to "Твит",
        "tweet_fab_item" to "Твитнуть",
        "tweet_title" to "Твит",
        "search_twitter" to "Поиск в Твиттере",
        "search_hint" to "Поиск в Твиттере",
        "ps__accessibility_retweet_broadcast_button" to "Ретвитнуть",
        "shortcut_retweet_tweet" to "Ретвитнуть",
        "social_you_retweeted" to "Вы ретвитнули",
        "composer_hint_self_thread" to "Добавить твит",
        "confirm_delete_shared_tweet_description" to "Вы уверены, что хотите удалить твит?",
        "confirm_delete_shared_tweet_title" to "Удалить твит",
        "conversation_control_reply_restricted_dialog_title" to "Твит не отправлен",
        "conversation_control_reply_restricted_error" to "Твит не отправлен. Ответы ограничены.",
        "conversations_alternative_reply_hint" to "Твитнуть ответ",
        "conversations_other_tweets" to "Другие твиты",
        "curation_i_dont_like_this_tweet" to "Мне не нравится этот твит",
        "date_posted" to "Дата твита",
        "post_tweet" to "Твитнуть",
        "deleted_tweet_title" to "Этот твит был удален.",
        "dm_sensitive_tweet_interstitial_header" to "Этот твит может содержать деликатный контент",
        "dm_untrusted_tweet_interstitial_header" to "Этот твит скрыт",
        "empty_profile_tweets_tab_title" to "Здесь будут ваши твиты",
        "feedback_action_report_tweet" to "Пожаловаться на твит",
        "feedback_tweet_unavailable" to "Этот твит недоступен.",
        "filter_item_tweets" to "Твиты",
        "filter_item_tweets_and_replies" to "Твиты и ответы",
        "profile_tab_title_timeline" to "Твиты",
        "users_turn_off_retweets" to "Отключить ретвиты",
        "tweets_retweet" to "Ретвитнуть",
        "tweets_retweeted" to "%s ретвитнуто",
        "tweets_undo_retweet_vertical" to "Отменить ретвит",
        "users_turn_on_retweets" to "Включить ретвиты",
        "ps__post_broadcast_twitter" to "Твит в Твиттере",
        "ps__retweet_broadcast_action" to "Ретвит в Твиттере",
        "retweeters_title" to "Ретвитнули",
        "icon_view_tweet_activity" to "Показать активность твита",
        "a11y_views_text" to "Показать активность твита",
        "tweet_analytics_title" to "Активность твита",
        "tweets_delete_title" to "Удалить твит",
        "share_tweet_sheet_title" to "Поделиться твитом",
        "view_quote_tweet" to "Посмотреть твит",
        "view_tweet" to "Посмотреть твит",
        "view_tweet_text" to "Посмотреть твит",
        "quote_label_subtitle" to "Добавить комментарий, фото или GIF перед отправкой",
        "retweet_label_subtitle" to "Поделиться твитом с читателями",
        "tweet_added_to_your_bookmarks" to "Твит добавлен в закладки",
        "tweet_author" to "Автор твита",
        "tweets_retweeted_accessibility_description" to "Твитнуто %s",
        "tweets_topic_accessibility_description" to "Твит из темы %s",
        "tweets_unauthorized_error" to "Нет прав для просмотра твитов.",
        "ps__posted_on_twitter" to "*%s* твитнул(а)",
        "ps__retweeted_on_twitter" to "*%s* ретвитнул(а)",
        "tweet_removed_from_your_bookmarks" to "Твит удален из закладок"
    )
}
