package crimera.patches.twitter.misc.bringbacktwitter.strings

object zh_rCN {
    val values = mapOf(
        "button_action_add_tweet" to "添加一条推文",
        "button_action_options_tweet" to "推文选项",
        "button_action_retweet" to "转推",
        "button_new_tweet" to "新推文",
        "button_status_retweeted" to "转推 (已转推)",
        "chrome_action_post" to "发推",
        "ps__share_post_tweet" to "推文",
        "rux_landing_page_title" to "发推",
        "tweet_fab_item" to "推文",
        "tweet_title" to "推文",
        "search_twitter" to "搜索 Twitter",
        "search_hint" to "搜索 Twitter",
        "ps__accessibility_retweet_broadcast_button" to "转推",
        "shortcut_retweet_tweet" to "转推",
        "social_you_retweeted" to "你转推了",
        "composer_hint_self_thread" to "添加另一条推文",
        "confirm_delete_shared_tweet_description" to "你确定要移除这条推文吗？",
        "confirm_delete_shared_tweet_title" to "移除推文",
        "conversation_control_reply_restricted_dialog_title" to "推文未发送",
        "conversation_control_reply_restricted_error" to "推文未发送。回复被限制。",
        "conversations_alternative_reply_hint" to "发布回复推文",
        "conversations_other_tweets" to "其他推文",
        "curation_i_dont_like_this_tweet" to "我不喜欢这条推文",
        "date_posted" to "发布的日期",
        "post_tweet" to "发推",
        "deleted_tweet_title" to "推文已删除。",
        "dm_sensitive_tweet_interstitial_header" to "此推文可能含有敏感内容",
        "dm_untrusted_tweet_interstitial_header" to "此推文已隐藏",
        "empty_profile_tweets_tab_title" to "你还没有发过推文",
        "feedback_action_report_tweet" to "报告推文",
        "feedback_tweet_unavailable" to "此推文不可用。",
        "filter_item_tweets" to "推文",
        "filter_item_tweets_and_replies" to "推文和回复",
        "profile_tab_title_timeline" to "推文",
        "users_turn_off_retweets" to "隐藏该用户的转推",
        "tweets_retweet" to "转推",
        "tweets_retweeted" to "%s 已转推",
        "tweets_undo_retweet_vertical" to "撤销转推",
        "users_turn_on_retweets" to "显示该用户的转推",
        "ps__post_broadcast_twitter" to "发到 Twitter 上",
        "ps__retweet_broadcast_action" to "转推到 Twitter 上",
        "retweeters_title" to "被转推",
        "icon_view_tweet_activity" to "查看推文动态",
        "a11y_views_text" to "查看推文动态",
        "tweet_analytics_title" to "推文动态",
        "tweets_delete_title" to "删除推文？",
        "share_tweet_sheet_title" to "分享推文",
        "view_quote_tweet" to "查看推文",
        "view_tweet" to "查看推文",
        "view_tweet_text" to "查看推文",
        "quote_label_subtitle" to "在分享这条推文之前添加评论、照片或 GIF。",
        "retweet_label_subtitle" to "把这条推文分享给你的关注者",
        "tweet_added_to_your_bookmarks" to "推文已添加到你的书签中",
        "tweet_author" to "推文作者",
        "tweets_retweeted_accessibility_description" to "由 %s 转推",
        "tweets_topic_accessibility_description" to "\"%s\" 话题的推文",
        "tweets_unauthorized_error" to "抱歉，你无权查看此推文。",
        "ps__posted_on_twitter" to "*%s* 发布到",
        "ps__retweeted_on_twitter" to "*%s* 转推到",
        "tweet_removed_from_your_bookmarks" to "推文已从你的书签中移除"
    )
}
