package crimera.patches.twitter.misc.bringbacktwitter.strings

object zh_rTW {
    val values = mapOf(
        "button_action_add_tweet" to "加入推文",
        "button_action_options_tweet" to "推文選項",
        "button_action_retweet" to "轉推",
        "button_new_tweet" to "新推文",
        "button_status_retweeted" to "轉推 (已轉推)",
        "chrome_action_post" to "發佈",
        "ps__share_post_tweet" to "推文",
        "rux_landing_page_title" to "推文",
        "tweet_fab_item" to "推文",
        "tweet_title" to "推文",
        "search_twitter" to "搜尋 Twitter",
        "search_hint" to "搜尋 Twitter",
        "ps__accessibility_retweet_broadcast_button" to "轉推",
        "shortcut_retweet_tweet" to "轉推",
        "social_you_retweeted" to "你已轉推",
        "composer_hint_self_thread" to "加入另一則推文",
        "confirm_delete_shared_tweet_description" to "你確定要移除此推文嗎？",
        "confirm_delete_shared_tweet_title" to "移除推文",
        "conversation_control_reply_restricted_dialog_title" to "推文未發送",
        "conversation_control_reply_restricted_error" to "推文未發送。回覆受到限制。",
        "conversations_alternative_reply_hint" to "推你的回覆",
        "conversations_other_tweets" to "其他推文",
        "curation_i_dont_like_this_tweet" to "我不喜歡這則推文",
        "date_posted" to "發佈日期",
        "post_tweet" to "推文",
        "deleted_tweet_title" to "此推文已被刪除。",
        "dm_sensitive_tweet_interstitial_header" to "此推文可能含有敏感內容",
        "dm_untrusted_tweet_interstitial_header" to "此推文已被隱藏",
        "empty_profile_tweets_tab_title" to "你還沒有發推文",
        "feedback_action_report_tweet" to "檢舉推文",
        "feedback_tweet_unavailable" to "此推文無法查看。",
        "filter_item_tweets" to "推文",
        "filter_item_tweets_and_replies" to "推文和回覆",
        "profile_tab_title_timeline" to "推文",
        "users_turn_off_retweets" to "關閉轉推",
        "tweets_retweet" to "轉推",
        "tweets_retweeted" to "%s 已轉推",
        "tweets_undo_retweet_vertical" to "取消轉推",
        "users_turn_on_retweets" to "開啟轉推",
        "ps__post_broadcast_twitter" to "在 Twitter 上發佈",
        "ps__retweet_broadcast_action" to "在 Twitter 上轉推",
        "retweeters_title" to "轉推由",
        "icon_view_tweet_activity" to "查看推文活動",
        "a11y_views_text" to "查看推文活動",
        "tweet_analytics_title" to "推文活動",
        "tweets_delete_title" to "要刪除推文嗎？",
        "share_tweet_sheet_title" to "分享推文",
        "view_quote_tweet" to "查看推文",
        "view_tweet" to "查看推文",
        "view_tweet_text" to "查看推文",
        "quote_label_subtitle" to "在分享此推文之前加入評論、相片或 GIF",
        "retweet_label_subtitle" to "與你的跟隨者分享此推文",
        "tweet_added_to_your_bookmarks" to "推文已加入至你的書籤",
        "tweet_author" to "推文作者",
        "tweets_retweeted_accessibility_description" to "已被 %s 轉推",
        "tweets_topic_accessibility_description" to "來自「%s」主題的推文",
        "tweets_unauthorized_error" to "抱歉，你沒有權限查看這些推文。",
        "ps__posted_on_twitter" to "*%s* 已發佈於",
        "ps__retweeted_on_twitter" to "*%s* 已轉推於",
        "tweet_removed_from_your_bookmarks" to "推文已從你的書籤中移除"
    )
}
