name: Build Custom Patches

on:
  push:
    branches: [ "build-test" ] # שינינו את זה כדי שירוץ אוטומטית על הבראנץ' הזמני!
  workflow_dispatch:

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Patches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean :patches:buildAndroid generatePatchesList

      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: custom-morphe-patches
          path: patches/build/libs/*